import assets from "./assets";

const cards = [
    { src: assets.image2, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image1, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image1, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image2, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image1, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image3, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location, 
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
    },
    { src: assets.image3, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image4, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
    { src: assets.image5, title: "Lorem Ipsum", author: "Lorem",heart_icon:assets.heart,location_icon:assets.location,
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur maximus lacus, non lacinia enim sodales sed.",
    button: "Explore",
     },
  ];

  export default cards;